Repository eco-dessert-platform/backend, pull requests merged in 2024-08, with the labels that each got.

#214 베스트 리뷰 오류 수정 및 구글 로그인 기능 구현
  src/main/java/com/bbangle/bbangle/member/controller/ProfileController.java
  src/main/java/com/bbangle/bbangle/member/service/MemberService.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepository.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
  src/main/java/com/bbangle/bbangle/token/jwt/TokenProvider.java
  src/main/java/com/bbangle/bbangle/token/oauth/infra/google/client/GoogleApiClient.java
  src/main/java/com/bbangle/bbangle/token/oauth/infra/google/client/GoogleMemberClient.java
  src/main/java/com/bbangle/bbangle/token/oauth/infra/google/dto/GoogleMemberResponse.java
  src/main/java/com/bbangle/bbangle/token/service/TokenService.java
  src/main/java/com/bbangle/bbangle/util/CookieUtil.java
  src/test/java/com/bbangle/bbangle/review/BestReviewSchedulerTest.java
Labels: enhancement

#217 🔧 프론트 요청사항에 따라 boards/{boardId} Response에 storeId 추가
  src/main/java/com/bbangle/bbangle/board/dao/BoardResponseDao.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardAndImageDto.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardDto.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
  src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
Labels: refactoring

#220 리뷰 수정 삭제 오류 해결 및 프론트 요청 처리
  src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
  src/main/java/com/bbangle/bbangle/review/controller/ReviewController.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewInfoResponse.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewSingleDto.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepository.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
  src/test/java/com/bbangle/bbangle/fixture/ReviewFixture.java
  src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
Labels: enhancement, refactoring

#221 🔧 스토어 디테일 API 리팩토링 및 필요한 컬럼 추가
  src/main/java/com/bbangle/bbangle/board/dto/BoardInfoDto.java
  src/main/java/com/bbangle/bbangle/board/dto/TagCategoryDto.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/repository/ProductQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/ProductRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/service/BoardService.java
  src/main/java/com/bbangle/bbangle/page/StoreDetailCustomPage.java
  src/main/java/com/bbangle/bbangle/store/controller/StoreController.java
  src/main/java/com/bbangle/bbangle/store/dto/BoardsInStoreDto.java
  src/main/java/com/bbangle/bbangle/store/dto/BoardsInStoreResponse.java
  src/main/java/com/bbangle/bbangle/store/dto/PopularBoardDto.java
  src/main/java/com/bbangle/bbangle/store/dto/PopularBoardResponse.java
  src/main/java/com/bbangle/bbangle/store/dto/StoreDetailBoardDto.java
  src/main/java/com/bbangle/bbangle/store/dto/StoreDetailProductDto.java
  src/main/java/com/bbangle/bbangle/store/dto/StoreResponse.java
  src/main/java/com/bbangle/bbangle/store/repository/StoreQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/store/repository/StoreRepository.java
  src/main/java/com/bbangle/bbangle/store/repository/StoreRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/store/service/StoreService.java
  src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryTest.java
  src/test/java/com/bbangle/bbangle/board/service/BestBoardServiceTest.java
  src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
  src/test/java/com/bbangle/bbangle/etc/repository/RedisRepositoryTest.java
  src/test/java/com/bbangle/bbangle/store/repository/StoreRepositoryTest.java
  src/test/java/com/bbangle/bbangle/store/service/StoreServiceTest.java
Labels: refactoring

#233 위시리스트 폴더에 있는 board임에도 board 전체 조회 시 isWished : false 로 나오는 에러 해결
  src/main/java/com/bbangle/bbangle/board/service/BoardService.java
  src/main/java/com/bbangle/bbangle/wishlist/controller/WishListBoardController.java
Labels: bug

#237 Push 알림 요청 보낼 시 restTemplate -> Firebase Admin SDK로 변경
  src/main/java/com/bbangle/bbangle/push/controller/PushController.java
  src/main/java/com/bbangle/bbangle/push/dto/FcmMessageDto.java
  src/main/java/com/bbangle/bbangle/push/dto/FcmTestDto.java
  src/main/java/com/bbangle/bbangle/push/service/FcmService.java
  src/main/java/com/bbangle/bbangle/push/service/PushService.java
Labels: enhancement

#240 Fix: 슬랙 메시지 보내기
  .github/workflows/cd-pipeline-dev-aws.yml
  .github/workflows/cicd.yml
  src/main/java/com/bbangle/bbangle/common/adaptor/slack/RealSlackAdaptor.java
  src/main/java/com/bbangle/bbangle/exception/GlobalControllerAdvice.java
Labels: bug

#241 [프론트 요청]재입고 및 빵켓팅 알림 재신청시 pushType이 null 이여도 처리
  src/main/java/com/bbangle/bbangle/board/repository/ProductQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/ProductRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/push/dto/CreatePushRequest.java
  src/main/java/com/bbangle/bbangle/push/dto/FcmRequest.java
  src/main/java/com/bbangle/bbangle/push/service/PushService.java
  src/main/java/com/bbangle/bbangle/token/oauth/OauthService.java
  src/test/java/com/bbangle/bbangle/push/service/PushServiceTest.java
Labels: refactoring
