Repository eco-dessert-platform/backend, pull requests merged in 2024-07, with the labels that each got.

#196 리뷰 테스트 코드 추가 및 리뷰 조회 시 이미지 엔티티로 변경
  src/main/java/com/bbangle/bbangle/image/dto/ImageDto.java
  src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
  src/main/java/com/bbangle/bbangle/image/service/S3Service.java
  src/main/java/com/bbangle/bbangle/page/ImageCustomPage.java
  src/main/java/com/bbangle/bbangle/review/domain/Review.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewImageUploadRequest.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewImageUploadResponse.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewInfoResponse.java
  src/main/java/com/bbangle/bbangle/review/dto/ReviewSingleDto.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/review/scheduler/BestReviewSelectionScheduler.java
  src/main/java/com/bbangle/bbangle/review/scheduler/ReviewScheduler.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
  src/test/java/com/bbangle/bbangle/AbstractIntegrationTest.java
  src/test/java/com/bbangle/bbangle/fixture/ReviewFixture.java
  src/test/java/com/bbangle/bbangle/review/BestReviewSchedulerTest.java
  src/test/java/com/bbangle/bbangle/review/ReviewServiceTest.java
  src/test/java/com/bbangle/bbangle/review/controller/ReviewControllerTest.java
  src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
Labels: enhancement

#199 오늘 주문 가능 상품 필터 조건 리팩토링
  src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/BoardFilterCreator.java
  src/test/java/com/bbangle/bbangle/board/repository/basic/cursor/CursorGeneratorTest.java
  src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
Labels: refactoring

#201 [프론트 요청] 리뷰 수정 시 이미지 처리 로직 리팩토링
  src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
  src/main/java/com/bbangle/bbangle/image/service/ImageService.java
  src/main/java/com/bbangle/bbangle/image/service/S3Service.java
  src/main/java/com/bbangle/bbangle/review/domain/Review.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
Labels: refactoring

#203 AWS 환경에서 작동할 CI/CD 파이프 라인 추가
  .github/workflows/cd-pipeline-dev-aws.yml
  .gitignore
  src/main/java/com/bbangle/bbangle/config/SwaggerConfig.java
Labels: refactoring

#204 리뷰 삭제 리팩토링 및 이미지 삭제 스케줄러 추가
  src/main/java/com/bbangle/bbangle/image/repository/ImageRepository.java
  src/main/java/com/bbangle/bbangle/image/service/ImageService.java
  src/main/java/com/bbangle/bbangle/review/repository/ReviewLikeRepository.java
  src/main/java/com/bbangle/bbangle/review/scheduler/SchedulerFactory.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
  src/test/java/com/bbangle/bbangle/review/BestReviewSchedulerTest.java
  src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
Labels: refactoring

#206 유저의 정보를 내려주는 기능 추가
  src/main/java/com/bbangle/bbangle/config/OctetStreamReadMsgConverter.java
  src/main/java/com/bbangle/bbangle/config/WebConfig.java
  src/main/java/com/bbangle/bbangle/member/controller/MemberController.java
  src/main/java/com/bbangle/bbangle/member/dto/MemberAssignResponse.java
  src/main/java/com/bbangle/bbangle/member/repository/SignatureAgreementRepository.java
  src/main/java/com/bbangle/bbangle/member/service/MemberService.java
  src/test/java/com/bbangle/bbangle/member/controller/MemberControllerTest.java
  src/test/java/com/bbangle/bbangle/member/service/MemberServiceTest.java
Labels: enhancement

#208 리뷰 많은 순 쿼리 오류 수정
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostWishedBoardQueryProviderResolver.java
Labels: bug
