Repository eco-dessert-platform/backend, pull requests merged in 2025-06, with the labels that each got.

#399 [Feat] 예외 발생 시 Stack Trace 로그 추가
  src/main/java/com/bbangle/bbangle/exception/GlobalControllerAdvice.java
Labels: feat

#401 스토어 게시물 조회 무한스크롤 추가
  src/main/java/com/bbangle/bbangle/board/controller/StoreController.java
  src/main/java/com/bbangle/bbangle/board/facade/StoreFacade.java
  src/main/java/com/bbangle/bbangle/board/service/StoreService.java
  src/main/java/com/bbangle/bbangle/board/service/dto/StoreInfo.java
  src/main/java/com/bbangle/bbangle/board/service/mapper/StoreInfoMapper.java
Labels: feat, refactoring

#402 [Refactor] JWT -> JWT쿠키
  src/main/java/com/bbangle/bbangle/config/CorsConfig.java
  src/main/java/com/bbangle/bbangle/config/CsrfConfig.java
  src/main/java/com/bbangle/bbangle/config/SecurityConfig.java
  src/main/java/com/bbangle/bbangle/config/WebMvcConfig.java
  src/main/java/com/bbangle/bbangle/config/WebOAuthSecurityConfig.java
  src/main/java/com/bbangle/bbangle/token/controller/TokenApiController.java
  src/main/java/com/bbangle/bbangle/token/dto/CreateAccessTokenRequest.java
  src/main/java/com/bbangle/bbangle/token/dto/CreateAccessTokenResponse.java
  src/main/java/com/bbangle/bbangle/token/jwt/TokenAuthenticationFilter.java
  src/main/java/com/bbangle/bbangle/token/jwt/TokenCookieProvider.java
  src/main/java/com/bbangle/bbangle/token/oauth/OauthController.java
Labels: refactoring

#403 [Fix] Swagger 200 응답에서 데이터 구조 보이게
  src/main/java/com/bbangle/bbangle/analytics/controller/AnalyticsController.java
  src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
  src/main/java/com/bbangle/bbangle/board/controller/BoardDetailController.java
  src/main/java/com/bbangle/bbangle/board/controller/ProductImgController.java
  src/main/java/com/bbangle/bbangle/board/controller/RandomBoardController.java
  src/main/java/com/bbangle/bbangle/board/controller/StoreController.java
  src/main/java/com/bbangle/bbangle/common/dto/SingleResult.java
  src/main/java/com/bbangle/bbangle/image/controller/ImageController.java
  src/main/java/com/bbangle/bbangle/member/controller/MemberController.java
  src/main/java/com/bbangle/bbangle/member/controller/ProfileController.java
  src/main/java/com/bbangle/bbangle/notification/controller/NotificationController.java
  src/main/java/com/bbangle/bbangle/preference/controller/PreferenceController.java
  src/main/java/com/bbangle/bbangle/push/controller/PushController.java
  src/main/java/com/bbangle/bbangle/review/controller/ReviewController.java
  src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
  src/main/java/com/bbangle/bbangle/survey/controller/SurveyController.java
  src/main/java/com/bbangle/bbangle/token/controller/TokenApiController.java
  src/main/java/com/bbangle/bbangle/wishlist/controller/WishListBoardController.java
  src/main/java/com/bbangle/bbangle/wishlist/controller/WishListFolderController.java
  src/main/java/com/bbangle/bbangle/wishlist/controller/WishListStoreController.java
Labels: bug
