Repository eco-dessert-platform/backend, pull requests merged in 2025-03, with the labels that each got.

#364 [Refactor] 보드 상세페이지 이미지 저장 방식 변경
  src/main/java/com/bbangle/bbangle/board/domain/BoardDetail.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardDetailQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
  src/main/java/com/bbangle/bbangle/util/HtmlUtils.java
  src/test/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryTest.java
  src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
  src/test/java/com/bbangle/bbangle/search/service/SearchServiceTest.java
  src/test/java/com/bbangle/bbangle/store/repository/StoreRepositoryTest.java
  src/test/java/com/bbangle/bbangle/util/HtmlUtilsTest.java
Labels: refactoring

#366 [Refactor] Board 이미지 테이블 리팩토링: ERD 개선 및 데이터 일관성 강화
  src/main/java/com/bbangle/bbangle/board/domain/Board.java
  src/main/java/com/bbangle/bbangle/board/domain/ProductImg.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardAndImageDto.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardAndImageResponses.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardImageDetailResponse.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardInfoDto.java
  src/main/java/com/bbangle/bbangle/board/recommend/repository/RecommendBoardQueryDSLRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardDetailRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepository.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/HighPriceBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/HighRatedBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/LowPriceBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostReviewedBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/MostWishedBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/PreferenceRecommendBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/RecentBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/basic/query/RecommendBoardQueryProviderResolver.java
  src/main/java/com/bbangle/bbangle/board/repository/folder/query/LowPriceBoardQueryProvider.java
  src/main/java/com/bbangle/bbangle/board/repository/folder/query/PopularBoardQueryProvider.java
  src/main/java/com/bbangle/bbangle/board/repository/folder/query/WishListRecentBoardQueryProvider.java
  src/main/java/com/bbangle/bbangle/board/service/BoardDetailService.java
  src/main/java/com/bbangle/bbangle/exception/BbangleErrorCode.java
  src/main/java/com/bbangle/bbangle/push/repository/PushQueryDSLRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/search/dto/SearchBoardResponseDto.java
  src/main/java/com/bbangle/bbangle/wishlist/repository/impl/WishListFolderRepositoryImpl.java
Labels: refactoring

#370 [Refactor] board-boardImg 매핑시 이미지 순서도 부여
  src/main/java/com/bbangle/bbangle/board/domain/ProductImg.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardDetailRequest.java
  src/main/java/com/bbangle/bbangle/board/repository/ProductImgRepository.java
  src/main/java/com/bbangle/bbangle/board/service/ProductImgService.java
  src/main/java/com/bbangle/bbangle/delivery/DeliveryCompany.java
Labels: refactoring

#371 [Refactor] 게시글 저장: CDN 붙여서 게시글 이미지 반환으로 리팩토링
  src/main/java/com/bbangle/bbangle/board/service/ProductImgService.java
  src/main/java/com/bbangle/bbangle/image/service/ImageService.java
  src/main/java/com/bbangle/bbangle/image/service/S3Service.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
Labels: refactoring

#374 [Refactor] 보드 조회: BoardPageGenerator 책임 분리
  src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
  src/main/java/com/bbangle/bbangle/board/controller/RandomBoardController.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardResponse.java
  src/main/java/com/bbangle/bbangle/board/dto/BoardResponses.java
  src/main/java/com/bbangle/bbangle/board/recommend/service/RecommendBoardService.java
  src/main/java/com/bbangle/bbangle/board/repository/util/BoardPageGenerator.java
  src/main/java/com/bbangle/bbangle/board/service/BoardService.java
  src/main/java/com/bbangle/bbangle/board/service/RandomBoardService.java
  src/main/java/com/bbangle/bbangle/common/page/BoardCustomPage.java
  src/main/java/com/bbangle/bbangle/common/page/CursorPageResponse.java
  src/main/java/com/bbangle/bbangle/common/page/CustomPage.java
  src/main/java/com/bbangle/bbangle/common/page/ImageCustomPage.java
  src/main/java/com/bbangle/bbangle/common/page/NotificationCustomPage.java
  src/main/java/com/bbangle/bbangle/common/page/ReviewCustomPage.java
  src/main/java/com/bbangle/bbangle/common/page/SearchCustomPage.java
  src/main/java/com/bbangle/bbangle/notification/repository/NotificationQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/notification/service/NotificationService.java
  src/main/java/com/bbangle/bbangle/review/service/ReviewService.java
  src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
  src/main/java/com/bbangle/bbangle/search/service/SearchService.java
  src/main/java/com/bbangle/bbangle/store/controller/StoreController.java
  src/main/java/com/bbangle/bbangle/store/service/StoreService.java
  src/main/java/com/bbangle/bbangle/wishlist/dto/WishListStoreCustomPage.java
  src/test/java/com/bbangle/bbangle/AbstractIntegrationTest.java
  src/test/java/com/bbangle/bbangle/board/controller/BoardControllerTest.java
  src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryCursorTest.java
  src/test/java/com/bbangle/bbangle/board/repository/BoardRepositoryTest.java
  src/test/java/com/bbangle/bbangle/board/repository/folder/BoardPageGeneratorTest.java
  src/test/java/com/bbangle/bbangle/board/repository/folder/query/WishListRecentBoardQueryProviderTest.java
  src/test/java/com/bbangle/bbangle/board/service/BoardServiceTest.java
  src/test/java/com/bbangle/bbangle/fixture/BoardFixture.java
  src/test/java/com/bbangle/bbangle/page/CursorPageResponseTest.java
  src/test/java/com/bbangle/bbangle/review/service/ReviewServiceTest.java
  src/test/java/com/bbangle/bbangle/store/service/StoreServiceMockTest.java
  src/test/java/com/bbangle/bbangle/store/service/StoreServiceTest.java
Labels: refactoring

#377 [Fix] CursorPageResponse 클래스 Redis 직렬화 에러
  src/main/java/com/bbangle/bbangle/common/page/CursorPageResponse.java
Labels: bug

#379 Flyway 버전 관리 폴더 생성
  src/main/resources/flyway/V10__app.sql
  src/main/resources/flyway/V11__app.sql
  src/main/resources/flyway/V12__app.sql
  src/main/resources/flyway/V13__app.sql
  src/main/resources/flyway/V14__app.sql
  src/main/resources/flyway/V1_app.sql
  src/main/resources/flyway/V2_app.sql
  src/main/resources/flyway/V3_app.sql
  src/main/resources/flyway/V4__app.sql
  src/main/resources/flyway/V5__app.sql
  src/main/resources/flyway/V6__app.sql
  src/main/resources/flyway/V7__app.sql
  src/main/resources/flyway/V8__app.sql
  src/main/resources/flyway/V9__app.sql
Labels: feat

#380 [Feat] Base64로 인코딩해주는 프로그램 구현
  encode-applications.ps1
Labels: feat

#383 [Fix] 테스트 코드 컴파일 에러
  src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
Labels: bug

#384 검색 게시판 조회 리팩토링
  src/main/java/com/bbangle/bbangle/board/controller/mapper/BoardDetailMapper.java
  src/main/java/com/bbangle/bbangle/board/dto/FilterRequest.java
  src/main/java/com/bbangle/bbangle/board/repository/BoardRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/common/mapstructure/Default.java
  src/main/java/com/bbangle/bbangle/common/page/CursorPagination.java
  src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
  src/main/java/com/bbangle/bbangle/search/controller/mapper/SearchMapper.java
  src/main/java/com/bbangle/bbangle/search/facade/SearchFacade.java
  src/main/java/com/bbangle/bbangle/search/repository/SearchFilterCreator.java
  src/main/java/com/bbangle/bbangle/search/repository/SearchQueryDSLRepository.java
  src/main/java/com/bbangle/bbangle/search/repository/SearchRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/search/repository/component/SearchFilter.java
  src/main/java/com/bbangle/bbangle/search/repository/component/SearchSort.java
  src/main/java/com/bbangle/bbangle/search/service/SearchService.java
  src/main/java/com/bbangle/bbangle/search/service/dto/SearchCommand.java
  src/main/java/com/bbangle/bbangle/search/service/dto/SearchInfo.java
  src/main/java/com/bbangle/bbangle/search/service/mapper/SearchInfoMapper.java
  src/main/java/com/bbangle/bbangle/wishlist/service/WishListBoardService.java
  src/test/java/com/bbangle/bbangle/search/controller/SearchControllerTest.java
  src/test/java/com/bbangle/bbangle/search/service/SearchServiceMockTest.java
  src/test/java/com/bbangle/bbangle/search/service/SearchServiceTest.java
Labels: refactoring
