Repository eco-dessert-platform/backend, pull requests merged in 2025-07, with the labels that each got.

#409 [Fix] PreferenceType.NONE 추가로 프론트 요청 대응
  src/main/java/com/bbangle/bbangle/preference/domain/PreferenceType.java
Labels: bug, feat

#412 board_detail 테이블 content컬럼 데이터 수정
  src/main/resources/flyway/V19__app.sql
Labels: feat

#413 📝 Pull Request: NULL 처리된 board_detail_id 정리
  src/main/resources/flyway/V20__app.sql
Labels: refactoring
