Repository eco-dessert-platform/backend, pull requests merged in 2025-05, with the labels that each got.

#389 쿼리 처리시간 측정 및 로깅 기능 추가
  build.gradle
  src/main/java/com/bbangle/bbangle/common/querylistener/CustomQueryLoggingListener.java
  src/main/java/com/bbangle/bbangle/common/querylistener/QueryTimerContext.java
  src/main/java/com/bbangle/bbangle/common/service/RequestTimeInterceptor.java
  src/main/java/com/bbangle/bbangle/config/DataSourceProxyConfig.java
Labels: feat

#391 [Fix] 위시리스트 최근순 조회 조인 누락 수정
  src/main/java/com/bbangle/bbangle/wishlist/repository/sort/strategy/RecentBoardInFolderSortRepository.java
Labels: wontfix

#392 게시글 조회 기본 제한 값 변경
  src/main/java/com/bbangle/bbangle/board/controller/BoardController.java
  src/main/java/com/bbangle/bbangle/board/facade/BoardFacade.java
  src/main/java/com/bbangle/bbangle/search/controller/SearchController.java
  src/main/java/com/bbangle/bbangle/search/controller/mapper/SearchMapper.java
  src/main/java/com/bbangle/bbangle/search/repository/SearchRepositoryImpl.java
  src/main/java/com/bbangle/bbangle/search/service/SearchService.java
  src/main/java/com/bbangle/bbangle/search/service/dto/SearchCommand.java
  src/main/java/com/bbangle/bbangle/search/service/dto/SearchInfo.java
  src/main/java/com/bbangle/bbangle/search/service/mapper/SearchInfoMapper.java
Labels: refactoring

#393 [Fix] 위시리스트 조회 이미지와 left join으로 수정
  src/main/java/com/bbangle/bbangle/wishlist/repository/WishListFolderRepositoryImpl.java
Labels: wontfix

#394 프로필 삭제 에러 수정
  src/main/java/com/bbangle/bbangle/member/domain/Member.java
  src/main/java/com/bbangle/bbangle/member/service/ProfileServiceImpl.java
Labels: refactoring

#395 [Fix] No constructor found ERROR 수정
  src/main/java/com/bbangle/bbangle/member/dto/MemberIdWithRoleDto.java
Labels: bug
